In [1]:
import tensorflow as tf


In [2]:
hello = tf.constant('hello world')

In [3]:
sess = tf.Session()

In [4]:
print(sess.run(hello))

b'hello world'


#hello world

In [5]:
s = 'String'

In [6]:
import numpy as np

In [7]:
np.random.randint(1,100)

75

In [8]:
arr = np.random.arange(1,100)

AttributeError: module 'numpy.random' has no attribute 'arange'

In [9]:
arr = np.arange(1,100)

In [10]:
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
arr.reshape(10,10)

ValueError: cannot reshape array of size 99 into shape (10,10)

In [24]:
my_list=[1,2,3,4,5,6]

In [25]:
arr=np.array(my_list)


In [26]:
arr


array([1, 2, 3, 4, 5, 6])

In [27]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
mat=np.arange(0,100).reshape(5,5)

ValueError: cannot reshape array of size 100 into shape (5,5)

In [17]:
mat = np.arange(0,100).reshape(10,10)

In [18]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [20]:
mat2=np.arange(0,100).reshape(10,10)

In [31]:
mat[0:5]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [32]:
my_data=(np.random.randomint(1,100))

AttributeError: module 'numpy.random' has no attribute 'randomint'

In [33]:
import numpy as np

In [40]:
my_data=np.random.randint(0,100,(10,10))

In [41]:
my_data

array([[61, 57, 88, 90, 61, 40, 43, 22, 72, 48],
       [77, 97,  8, 48, 66, 44, 43, 49, 76, 81],
       [40,  7, 73, 92, 42, 59, 92, 42, 18, 64],
       [21, 39, 22, 94, 55, 84, 23, 82, 19, 23],
       [26, 54, 61, 96, 96, 14, 79, 47, 37, 27],
       [37, 35, 61, 29, 27, 82, 75, 33, 82,  2],
       [52, 83, 25, 62,  3, 94, 66, 80, 76, 49],
       [ 9, 36, 83, 89, 85, 73,  5, 85, 14, 89],
       [45, 43,  5, 16, 59, 92, 80, 51, 83, 19],
       [22, 93, 17, 82, 54,  4, 38, 40, 67, 72]])

In [42]:
import pandas as pd

In [43]:
data=pd.DataFrame(my_data)

In [44]:
data

0   1   2   3   4   5   6   7   8   9
0  61  57  88  90  61  40  43  22  72  48
1  77  97   8  48  66  44  43  49  76  81
2  40   7  73  92  42  59  92  42  18  64
3  21  39  22  94  55  84  23  82  19  23
4  26  54  61  96  96  14  79  47  37  27
5  37  35  61  29  27  82  75  33  82   2
6  52  83  25  62   3  94  66  80  76  49
7   9  36  83  89  85  73   5  85  14  89
8  45  43   5  16  59  92  80  51  83  19
9  22  93  17  82  54   4  38  40  67  72