In [5]:
import tensorflow as tf

In [6]:
print(tf.__version__)

1.3.0


In [7]:
hello=tf.constant('hello ')

In [1]:
world=tf.constant('world')

NameError: name 'tf' is not defined

In [9]:
result=hello + world

In [10]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [11]:
with tf.Session() as sess:
        result=sess.run(hello+world)

In [12]:
result

b'hello world'

In [14]:
a=tf.constant([[4,2],
             [4,9]])

In [15]:
b=tf.constant([[5],[9]])
             

In [16]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [17]:
c=tf.matmul(a,b)

In [18]:
sess=tf.InteractiveSession()

In [19]:
c.eval()

array([[ 38],
       [101]])

In [20]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [21]:
myrandn.eval()

array([[-0.00114173,  0.46568453,  0.68876654, -0.25752237],
       [ 0.28548825,  0.10265905,  0.2305706 ,  0.08778203],
       [ 0.05985438, -0.03647553,  0.21243909,  0.72541493],
       [ 0.48145306, -0.3954944 , -0.09313023,  0.0459156 ]], dtype=float32)

In [22]:
myranu = tf.random_uniform((4,4),minval=5)

In [23]:
myranu.eval()

array([[ 4.99966908,  1.1337595 ,  1.13249445,  1.74965096],
       [ 2.85764408,  4.06292772,  3.80201769,  3.31470776],
       [ 4.25542927,  1.41709375,  4.04332161,  2.28178596],
       [ 3.84366226,  3.72061539,  1.38122129,  4.21209097]], dtype=float32)

In [31]:
fill_mat = tf.fill((5,5),9) 

In [32]:
sess.run(fill_mat)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])